CREATE TABLE IF NOT EXISTS public.roles
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    role character varying(20) COLLATE pg_catalog."default",
    CONSTRAINT roles_pkey PRIMARY KEY (id)
);

INSERT INTO public.roles(id, role) VALUES (1, 'ROLE_ADMIN');
INSERT INTO public.roles(id, role) VALUES (2, 'ROLE_MODERATOR');
INSERT INTO public.roles(id, role) VALUES (3, 'ROLE_USER');

COMMIT;